import React from 'react'
import { Ubuntu } from 'next/font/google'
import '@/styles/global.css'

export const metadata = {
  title: 'Community Core',
  description: 'Generated by Next.js',
}

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  variable: '--font-ubuntu',
});

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={ubuntu.className}>
      <head>
        <link
            href="https://fonts.googleapis.com/css2?family=Flamenco:wght@300;400&display=swap"
            rel="stylesheet"
        />
        <title>{metadata.title}</title>
      </head>
      <body>{children}</body>
    </html>
  )
}
